### ISSUE TITLE
how to submit?

### ISSUE THREAD

**Issue by ch3cook-fdu** [daveredrum/faster-captioning#1]
What's the code for submitting results on official benchmark?

https://kaldir.vc.in.tum.de/scanrefer_benchmark/benchmark_captioning.php?sortby=dmAP_0_5

It would be helpful if related codes are shared.

**Comment by daveredrum** [comment]
Hi @ch3cook-fdu, you can use [this script](https://github.com/daveredrum/faster-captioning/blob/main/benchmark/predict.py) to  generate JSON file for submission. Don't forget to zip it before you submit.

**Comment by ch3cook-fdu** [comment]
Thanks!
