### ISSUE TITLE
Notice there are three scenes missing in the test set?

### ISSUE THREAD

**Issue by ch3cook-fdu** [daveredrum/faster-captioning#3]
Missing 'scene0789_00', 'scene0792_00', 'scene0806_00' for testing dense captioning, is predictions on these scenes required?

**Comment by daveredrum** [comment]
Hi @ch3cook-fdu, those scenes after ``scene0707_00'' are from the hidden test set. You don't need those scenes for training and validation, unless you would like to submit your predictions to the public benchmark.

**Comment by ch3cook-fdu** [comment]
yes i'm testing the network for submission, and i notice that the generated file consists of 97 scenes rather than 100, which is the size of whole scannet test set.

is it normal?

**Comment by daveredrum** [comment]
Those scenes should be included in the submission. Could you check if you downloaded the whole ScanNet v2?

**Comment by ch3cook-fdu** [comment]
I notice that it's because the scanrefer test set only contains annotations for 97 scenes in the test set, so would i upload results for 97 scenes or 100 scenes?

**Comment by daveredrum** [comment]
Oh, then it's definitely okay to omit those three scenes - Sorry for the confusion. I totally forgot that we excluded those scenes, probably because there is limited context to work on in those scenes.

**Comment by ch3cook-fdu** [comment]
understood! thanks for clarification!
